broadinstitute/dagster-utils

.github/workflows/cut-tag-main.yaml
The action we're using to automatically create new tags assumes that your default branch is 'master' and this repo's default branch is 'main'.
[X] I have described my changes in detail in my commit message, breaking things down as described in the [README](README.md)
=> Mark main as a release branch for tagging purposes

.github/workflows/publish-tag.yaml
The Github Actions user doesn't trigger certain types of event in order to prevent infinite loops. This includes "push" events, which means that we can't bind the publishing workflow to the "push tag" event if a github action is responsible for pushing the tag. Instead, we bind to the tag creation event.
[ ] I have described my changes in detail in my commit message, breaking things down as described in the [README](README.md)
=> Trigger publish action on tag creation

.github/workflows/publish-tag.yaml, .gitignore, pyproject.toml
Type hints aren't available from a compiled package by default, so we need to explicitly build and bundle our stubs or Mypy can't read them.
[X] I have described my changes in detail in my commit message, breaking things down as described in the [README](README.md)
=> Generate and include type stubs in published package

.github/PULL_REQUEST_TEMPLATE.md, dagster_utils/contrib/google.py, dagster_utils/resources/bigquery.py, dagster_utils/resources/google_storage.py, dagster_utils/resources/jade_data_repo.py
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1699)
Our resource mocks need some changes to support DSPDC-1699 (data file loading).
* Adds a helper to our google support module that constructs a valid GS path from a separate bucket and prefix
* Adds new methods to the datarepo client
* Adjusts the noop bigquery client to be a Mock spec'ed by `google.cloud.bigquery.Client`
=> Changes to support dspdc-1699

README.md, dagster_utils/contrib/google.py, dagster_utils/resources/bigquery.py, dagster_utils/resources/google_storage.py, dagster_utils/resources/jade_data_repo.py, pyproject.toml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1752)
New features:
* contrib.google.default_google_access_token now optionally accepts a Credentials object, which it will use to generate a token
* All GCP resources (and resources that authenticate using GCP) now automatically refresh tokens each time they make a request.
Bugfixes:
* contrib.google.authorized_session now correctly passes a Credentials object to the constructor rather than a raw access token
[X] I have described my changes in detail in my commit message, breaking things down as described in the [README](README.md)
=> Alter GCP resources to use authorized sessions, auto-refresh credentials used in data repo client

dagster_utils/resources/jade_data_repo.py, pyproject.toml
* Introduced a bug by not correctly matching variable names in data repo config
* Makes 'em match
=> Fix mismatched variable name in data repo API config

dagster_utils/resources/data_repo/jade_data_repo.py, dagster_utils/resources/slack.py, pyproject.toml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1789)
As part of implementing some small quality-of-life improvements for our HCA snapshot job, I discovered we don't accept blocks for our slack client (for fancier slack notifications), nor does the "noop" Jade client expose the needed `create_snapshot` methods for test mode. 
* Adds those methods and updates the slack client with a `blocks` parameter.
=> Update slack client to allow blocks and update noopjadeclient

README.md
We need to develop against local versions of dagster-utils, this updates the readme with relevant instructions.
=> Update README with instructions on how to develop locally

dagster_utils/resources/beam/beam_runner.py, dagster_utils/resources/beam/dataflow_beam_runner.py, dagster_utils/resources/beam/k8s_beam_runner.py, dagster_utils/resources/beam/local_beam_runner.py, dagster_utils/resources/beam/noop_beam_runner.py, pyproject.toml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1781)
Refactored resources to create a Beam package with a separate file per runner.
Renamed the DataflowBeamRunner as K8sDataflowBeamRunner for accuracy.
Created a separate DataflowBeamRunner resource as needed for the DAP project.
Created a BeamRunner protocol to standardize the arguments passed in to the run function.
Refactored all of the runners to adhere to the new BeamRunner protocol.
Version bumped to 0.5.0 - note that changes here will break existing projects that use the beam resources package (HCA).
=> Refactoring Beam resources

.github/workflows/validate-python.yaml, dagster_utils/tests/resources/data_repo/test_jade_data_repo.py, pytest.ini
The Jade data repo connectivity test relies on correctly activated local gcloud dev credentials, which is cumbersome.
* Marks the test to only run in our CI environment where we know we have creds setup correctly
=> Mark test as ci-only

dagster_utils/resources/beam/beam_runner.py, dagster_utils/resources/beam/dataflow_beam_runner.py, dagster_utils/resources/beam/k8s_beam_runner.py, dagster_utils/resources/beam/local_beam_runner.py, dagster_utils/resources/beam/noop_beam_runner.py, pyproject.toml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1798)
We need to backport the beam runner changes to HCA. One wrinkle is that the K8S beam runner expects a job name; our initial approach was to pass that through as an arg in the arg dict. However, the local and dataflow beam runner implementations both automatically convert all args in the arg dict to scala direct runner args. Direct runner in turn errors out when it encounters the unexpected jobName variable.
* Rather than adding special case code to the local and dataflow beam runners, I've opted to add `job_name` as an optional arg to the BeamRunner protocol's `run` method.
=> Make job name a parameter of BeamRunner::run()

dagster_utils/resources/sam.py, dagster_utils/tests/resources/test_sam.py, pyproject.toml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1795)
We are getting an HTTP 415 error code when setting snapshots public. I have determined this is due to us not sending an `Content-type: application/json` header in our request.
* Explicitly set the needed header in the request (python `requests` will generally do the right thing if you send a `json={...}` payload, but we're sending a raw `data=true` value which short-circuits the automatic setting of the header)
* Bumps the version
=> Force setting of content-type: application/json for SAM to avoid http 415 error

dagster_utils/resources/beam/k8s_beam_runner.py, pyproject.toml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1831)
We cannot run beam jobs in K8S as the K8S beam runner is attempting to load a config file that is non-existent in all non-local cases.
* Adds an optional parameter that will load the K8S config via in-cluster context if set.
=> Optionally load K8S config via incluster settings

dagster_utils/resources/beam/k8s_beam_runner.py, pyproject.toml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1891)
The `load_incluster_config` param was flipped to False while I tested locally, and I failed to flip it back to True. This will break downstream k8s runners. 
* Flips back to `True` by default, and allows the config to be set by downstream clients to avoid this situation in the future.
=> Flip load_incluster_config to true by default and externalize

dagster_utils/resources/sam.py, dagster_utils/tests/resources/test_sam.py, pyproject.toml
We need the ability to mark a snapshot private.
* Updates the SAM client method to take a bool `status` parameter
=> Add ability to set a snapshot to private

dagster_utils/contrib/data_repo/jobs.py, pyproject.toml
It's difficult to determine which job ID failed when there are many jobs executing in an ingest. We should output the job id as part of the error message.
* Adds the job ID to the error message
=> Add job id to error message to speed debugging

.github/workflows/cut-tag-main.yaml, .github/workflows/publish-tag.yaml
[Relevant ticket](https://broadworkbench.atlassian.net/browse/FE-359)
is a follow on to #36 - the actions couldn't find python 3.1 >> needed to put 3.10 in quotes.
=> FE-359 upgrade dagster utils to 3.10 ('3.10', apparently)

.github/workflows/cut-tag-main.yaml, .github/workflows/publish-tag.yaml, .github/workflows/validate-python.yaml, .pre-commit-config.yaml, README.md, pyproject.toml
[Relevant ticket](https://broadworkbench.atlassian.net/browse/FE-359)
**Breaking changes**
- downgrade to python ~3.9 to match hca-ingest
- upgrade to dagster 0.13.0
**Known Issues**
- Cut tag & Publish tag actions are broken, we need to set up GSM - this does not impact the use dagster-utils, but it does require manual tag, release & publish to PyPi
=> FE-359 upgrade to Dagster 0.13.0

.github/workflows/cut-tag-main.yaml, .github/workflows/publish-tag.yaml, .github/workflows/validate-python.yaml, pyproject.toml
[Relevant ticket](https://broadworkbench.atlassian.net/browse/FE-375)
**Breaking changes**
- updates Python to 3.10
- updates Dagster to 0.14
**Known Issues**
Cut tag & Publish tag actions are broken, we need to set up GSM - this does not impact the use of dagster-utils, but it does require manual tag, release & publish to PyPi
=> FE-375 updating to python 3.10 and Dagster 0.14

dagster_utils/resources/slack.py, pyproject.toml
[Relevant ticket](https://broadworkbench.atlassian.net/browse/FE-374)
**Breaking Changes**
- updates [Dagster to 0.15](https://github.com/dagster-io/dagster/blob/master/MIGRATION.md#migrating-to-0150)
**Known Issues**
Cut tag & Publish tag actions are broken, we need to set up GSM - this does not impact the use of dagster-utils, but it does require manual tag, release & publish to PyPi
This work is in support of upgrading the hca ingest workflow to Dagster 0.15 [FE-380](https://broadworkbench.atlassian.net/browse/FE-380)
[FE-380]: https://broadworkbench.atlassian.net/browse/FE-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update package version to 2.0.0a6, and update Dagster to 0.15
